### ISSUE TITLE
Issues with Ruby 2.4

### ISSUE THREAD

**Issue by matthutchinson** [davetron5000/methadone#110]
I maintain the [lolcommits](https://github.com/mroth/lolcommits) gem, (which has been using methadone for some years now). I'm working on making it Ruby 2.4.0 friendly.  Among other issues I found that methadone was blowing up with this error when calling `go!`:

```
NoMethodError: undefined method `level' for nil:NilClass
  /u/code/lolcommits/vendor/bundle/gems/methadone-1.9.4/lib/methadone/cli_logger.rb:102:in `level='
  /Users/matt/.rbenv/versions/2.4.0/lib/ruby/2.4.0/logger.rb:380:in `initialize'
  /u/code/lolcommits/vendor/bundle/gems/methadone-1.9.4/lib/methadone/cli_logger.rb:85:in `initialize'
  /u/code/lolcommits/vendor/bundle/gems/methadone-1.9.4/lib/methadone/cli_logging.rb:37:in `new'
  /u/code/lolcommits/vendor/bundle/gems/methadone-1.9.4/lib/methadone/cli_logging.rb:37:in `logger'
  /u/code/lolcommits/vendor/bundle/gems/methadone-1.9.4/lib/methadone/main.rb:405:in `rescue in call_main
  /u/code/lolcommits/vendor/bundle/gems/methadone-1.9.4/lib/methadone/main.rb:395:in `call_main'
  /u/code/lolcommits/vendor/bundle/gems/methadone-1.9.4/lib/methadone/main.rb:167:in `go!'
```

Digging into this..  it turns out that `Logger` in Ruby 2.4.0 has a new `initialize`method, that takes new optional args and calls to set the logger level (defaulting to DEBUG). Here's the new method signature..

```
# lib/ruby/2.4.0/logger.rb
def initialize(logdev, shift_age = 0, shift_size = 1048576, level: DEBUG,
               progname: nil, formatter: nil, datetime_format: nil,      
               shift_period_suffix: '%Y%m%d')                            
```

This would be fine, except that `Methadone::CLILogger` overrides the `level=` method and expects that a `@stderr_logger` variable is set.  The fix for this I'd propose, would be to set this instance variable first, before calling `super(log_device)`.  That way, it will always be present, when the Ruby `Logger` calls to set `level=` in it's own initializer.

I was preparing a fork/PR for this change when I noticed these:

* The `sdoc` gem in your gemspec, requires an older version of json (1.8.3) which will not compile under Ruby 2.4 - switching to use `sdoc ~> 1.0.0.rc1` (released on Christmas day) solves this (you could use this until the gem author releases a 1.0 final). I checked and `rake rdoc` works fine with this.

* Ruby 2.4 outputs warnings when you use `Fixnum` or `Bignum` constants causing a bunch of your tests to fail, swapping these out with `Integer` solves this (and is backward compatible with older Rubies)

---

[This article](https://blog.blockscore.com/new-features-in-ruby-2-4/) explains whats new in Ruby 2.4 (including the above changes I mentioned).

I'll issue a [PR](https://github.com/davetron5000/methadone/pull/111) in a few secs, hopefully it will pass Travis for all Rubies...

**Comment by davetron5000** [comment]
Yeah, on Travis it seemed like it couldn't install the json gem.  Not sure if that's just Travis or if there are deeper issues.  Please LMK if you find problems

**Comment by matthutchinson** [comment]
Alll green on Travis ! 💚 

(apologies for the whitespace changes in my PR, my Vim is set to truncate leading whitespace)

**Comment by davetron5000** [comment]
This was fixed by #111
